apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-tls-secret
spec:
  secretName: my-tls-dev-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - keycloak-dev.apps.cluster-hrdgj.hrdgj.sandbox1859.opentlc.com
