kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: keycloak-rollout-run-
spec:
  pipelineRef:
    name: keycloak-pipeline
  params:
    - name: "url"
      value: "https://github.com/masauve/keycloak-x-openshift"
  workspaces:
    - name: buildworkspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
